# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

api_keys: &api_keys
  google_api_key:  <%= ENV['GOOGLE_API_KEY'] %>

development:
  <<: *api_keys
  secret_key_base: 3328c2e58b135755160ae3791fe9cf36f70ba78809b55c7cd500fdf7cc2152ce4dec0d275da2a86e8e3dadf93475a14ea844766e7aa4cfd51c8e5e926f25cd8c

test:
  <<: *api_keys
  secret_key_base: 65c30d657a1c0b69ec2fe927bac924e684b1c8bda5e014bc279ac86b41ec4c57461968382fadf33a0fc6e0ed6ac17a72b95c2905cb3356a8c871453db2baf180

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  <<: *api_keys
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
